apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-demo-ingress
  namespace: spring-demo
spec:
  ingressClassName: nginx
  rules:
    - host: spring.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: spring-demo-service
                port:
                  number: 8080